### ISSUE TITLE
请问可以提供一下yolo v5的utils.py文件吗

### ISSUE THREAD

**Issue by zimenglic** [ELKYang/RailWay_Detection#1]
请问直接运行yolo v5中的detect文件可以实现障碍物检测吗？直接运行yolo v5中的detect.py会有缺少utils.py的错误

**Comment by ELKYang** [comment]
不是直接运行yolo v5, 具体使用参照RailwayDetection文件夹下的test.ipynb

**Comment by zimenglic** [comment]
你好，您的来信我已收到。我会尽快给您回复。
